### ISSUE TITLE
Githubなどのリンクが右下にない

### ISSUE THREAD

**Issue by Pleurotus-eryngii** [syuchan1005/OekakinoMorihiko#4]
追加中かもしれませんが右下部のTwitterの近くにGithubのリンクがあるといいかな、という案が出ていたので

**Comment by Pleurotus-eryngii** [comment]
https://github.com/syuchan1005/OekakinoMorihiko/pull/5

**Comment by syuchan1005** [comment]
Margeしたのでcloseします
