### ISSUE TITLE
新規接続者へのキャンバス送信

### ISSUE THREAD

**Issue by siketyan** [syuchan1005/OekakinoMorihiko#8]
JavaScriptでcanvasオブジェクトを何らかにシリアライズして送信すれば可能？
http://stackoverflow.com/questions/22228552/serialize-canvas-content-to-arraybuffer-and-deserialize-again

**Comment by syuchan1005** [comment]
現在
[実装部分](https://github.com/syuchan1005/OekakinoMorihiko/blob/master/src/main/java/com/github/syuchan1005/oekakinomorihiko/WebSocketHandler.java#L40)
にコメントアウトしてあります。

これはJavascript Image-pngの文字列を想定している=Binary送信なので圧縮を考えるのが手ですかね
圧縮することも出来ますが一部のブラウザ(!Chromium)では解凍が出来ない場合があるので各ブラウザの対応待ちです
